spring:
  datasource:
    url: jdbc:mysql://192.168.1.83:3306/springbootspringcloud
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.83:8761/eureka/ 
  instance:
    instance-id: instanciaProductos1
    hostname: 192.168.1.83
    non-secure-port: 8090

server:
  port: 8090
