spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootspringcloud
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ 
  instance:
    instance-id: instanciaPedidos1

server:
  port: 8081
