spring:
  datasource:
    url: jdbc:mysql://192.168.1.83:3306/springbootspringcloud
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ 
  instance:
    instance-id: instanciaPedidos1
    hostname: 192.168.1.83
    non-secure-port: 8091
    
server:
  port: 8091
