spring:
  datasource:
    url: jdbc:mysql://192.168.1.83:3306/springbootspringcloud
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
 
server:
  port: 8091
 
springdoc:
  packagesToScan: com.darioabuin.serviciocursos.controller
  pathsToMatch: /**

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.83:8761/eureka/ 
  instance:
    instance-id: curso1
    hostname: 192.168.1.83
